//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("TiendaRegalosModel", "FK_Regalos_Categorias", "Categorias", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TiendaRegalosMVC.Models.Categoria), "Regalos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TiendaRegalosMVC.Models.Regalo), true)]
[assembly: EdmRelationshipAttribute("TiendaRegalosModel", "FK_Pedidos_Clientes", "Clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TiendaRegalosMVC.Models.Cliente), "Pedidos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TiendaRegalosMVC.Models.Pedido), true)]
[assembly: EdmRelationshipAttribute("TiendaRegalosModel", "FK_RegalosPedido_Pedidos", "Pedidos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TiendaRegalosMVC.Models.Pedido), "RegalosPedido", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TiendaRegalosMVC.Models.RegaloPedido), true)]
[assembly: EdmRelationshipAttribute("TiendaRegalosModel", "FK_RegalosPedido_Regalos", "Regalos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TiendaRegalosMVC.Models.Regalo), "RegalosPedido", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TiendaRegalosMVC.Models.RegaloPedido), true)]

#endregion

namespace TiendaRegalosMVC.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class TiendaRegalosEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto TiendaRegalosEntities usando la cadena de conexión encontrada en la sección 'TiendaRegalosEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public TiendaRegalosEntities() : base("name=TiendaRegalosEntities", "TiendaRegalosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto TiendaRegalosEntities.
        /// </summary>
        public TiendaRegalosEntities(string connectionString) : base(connectionString, "TiendaRegalosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto TiendaRegalosEntities.
        /// </summary>
        public TiendaRegalosEntities(EntityConnection connection) : base(connection, "TiendaRegalosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Categoria> Categorias
        {
            get
            {
                if ((_Categorias == null))
                {
                    _Categorias = base.CreateObjectSet<Categoria>("Categorias");
                }
                return _Categorias;
            }
        }
        private ObjectSet<Categoria> _Categorias;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Cliente> Clientes
        {
            get
            {
                if ((_Clientes == null))
                {
                    _Clientes = base.CreateObjectSet<Cliente>("Clientes");
                }
                return _Clientes;
            }
        }
        private ObjectSet<Cliente> _Clientes;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Pedido> Pedidos
        {
            get
            {
                if ((_Pedidos == null))
                {
                    _Pedidos = base.CreateObjectSet<Pedido>("Pedidos");
                }
                return _Pedidos;
            }
        }
        private ObjectSet<Pedido> _Pedidos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Regalo> Regalos
        {
            get
            {
                if ((_Regalos == null))
                {
                    _Regalos = base.CreateObjectSet<Regalo>("Regalos");
                }
                return _Regalos;
            }
        }
        private ObjectSet<Regalo> _Regalos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<RegaloPedido> RegalosPedido
        {
            get
            {
                if ((_RegalosPedido == null))
                {
                    _RegalosPedido = base.CreateObjectSet<RegaloPedido>("RegalosPedido");
                }
                return _RegalosPedido;
            }
        }
        private ObjectSet<RegaloPedido> _RegalosPedido;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Categorias. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCategorias(Categoria categoria)
        {
            base.AddObject("Categorias", categoria);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Clientes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToClientes(Cliente cliente)
        {
            base.AddObject("Clientes", cliente);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Pedidos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPedidos(Pedido pedido)
        {
            base.AddObject("Pedidos", pedido);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Regalos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToRegalos(Regalo regalo)
        {
            base.AddObject("Regalos", regalo);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet RegalosPedido. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToRegalosPedido(RegaloPedido regaloPedido)
        {
            base.AddObject("RegalosPedido", regaloPedido);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TiendaRegalosModel", Name="Categoria")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Categoria : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Categoria.
        /// </summary>
        /// <param name="idCategoria">Valor inicial de la propiedad IdCategoria.</param>
        /// <param name="nombreCategoria">Valor inicial de la propiedad NombreCategoria.</param>
        public static Categoria CreateCategoria(global::System.Int32 idCategoria, global::System.String nombreCategoria)
        {
            Categoria categoria = new Categoria();
            categoria.IdCategoria = idCategoria;
            categoria.NombreCategoria = nombreCategoria;
            return categoria;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCategoria
        {
            get
            {
                return _IdCategoria;
            }
            set
            {
                if (_IdCategoria != value)
                {
                    OnIdCategoriaChanging(value);
                    ReportPropertyChanging("IdCategoria");
                    _IdCategoria = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCategoria");
                    OnIdCategoriaChanged();
                }
            }
        }
        private global::System.Int32 _IdCategoria;
        partial void OnIdCategoriaChanging(global::System.Int32 value);
        partial void OnIdCategoriaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreCategoria
        {
            get
            {
                return _NombreCategoria;
            }
            set
            {
                OnNombreCategoriaChanging(value);
                ReportPropertyChanging("NombreCategoria");
                _NombreCategoria = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreCategoria");
                OnNombreCategoriaChanged();
            }
        }
        private global::System.String _NombreCategoria;
        partial void OnNombreCategoriaChanging(global::System.String value);
        partial void OnNombreCategoriaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TiendaRegalosModel", "FK_Regalos_Categorias", "Regalos")]
        public EntityCollection<Regalo> Regalos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Regalo>("TiendaRegalosModel.FK_Regalos_Categorias", "Regalos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Regalo>("TiendaRegalosModel.FK_Regalos_Categorias", "Regalos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TiendaRegalosModel", Name="Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cliente : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Cliente.
        /// </summary>
        /// <param name="idCliente">Valor inicial de la propiedad IdCliente.</param>
        /// <param name="nombreCliente">Valor inicial de la propiedad NombreCliente.</param>
        /// <param name="direccion">Valor inicial de la propiedad Direccion.</param>
        /// <param name="ciudad">Valor inicial de la propiedad Ciudad.</param>
        /// <param name="email">Valor inicial de la propiedad Email.</param>
        public static Cliente CreateCliente(global::System.Int32 idCliente, global::System.String nombreCliente, global::System.String direccion, global::System.String ciudad, global::System.String email)
        {
            Cliente cliente = new Cliente();
            cliente.IdCliente = idCliente;
            cliente.NombreCliente = nombreCliente;
            cliente.Direccion = direccion;
            cliente.Ciudad = ciudad;
            cliente.Email = email;
            return cliente;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCliente
        {
            get
            {
                return _IdCliente;
            }
            set
            {
                if (_IdCliente != value)
                {
                    OnIdClienteChanging(value);
                    ReportPropertyChanging("IdCliente");
                    _IdCliente = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCliente");
                    OnIdClienteChanged();
                }
            }
        }
        private global::System.Int32 _IdCliente;
        partial void OnIdClienteChanging(global::System.Int32 value);
        partial void OnIdClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreCliente
        {
            get
            {
                return _NombreCliente;
            }
            set
            {
                OnNombreClienteChanging(value);
                ReportPropertyChanging("NombreCliente");
                _NombreCliente = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreCliente");
                OnNombreClienteChanged();
            }
        }
        private global::System.String _NombreCliente;
        partial void OnNombreClienteChanging(global::System.String value);
        partial void OnNombreClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ciudad
        {
            get
            {
                return _Ciudad;
            }
            set
            {
                OnCiudadChanging(value);
                ReportPropertyChanging("Ciudad");
                _Ciudad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ciudad");
                OnCiudadChanged();
            }
        }
        private global::System.String _Ciudad;
        partial void OnCiudadChanging(global::System.String value);
        partial void OnCiudadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TiendaRegalosModel", "FK_Pedidos_Clientes", "Pedidos")]
        public EntityCollection<Pedido> Pedidos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Pedido>("TiendaRegalosModel.FK_Pedidos_Clientes", "Pedidos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Pedido>("TiendaRegalosModel.FK_Pedidos_Clientes", "Pedidos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TiendaRegalosModel", Name="Pedido")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pedido : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Pedido.
        /// </summary>
        /// <param name="idPedido">Valor inicial de la propiedad IdPedido.</param>
        /// <param name="fechaPedido">Valor inicial de la propiedad FechaPedido.</param>
        /// <param name="importe">Valor inicial de la propiedad Importe.</param>
        /// <param name="clientesIdCliente">Valor inicial de la propiedad ClientesIdCliente.</param>
        public static Pedido CreatePedido(global::System.Int32 idPedido, global::System.DateTime fechaPedido, global::System.Decimal importe, global::System.Int32 clientesIdCliente)
        {
            Pedido pedido = new Pedido();
            pedido.IdPedido = idPedido;
            pedido.FechaPedido = fechaPedido;
            pedido.Importe = importe;
            pedido.ClientesIdCliente = clientesIdCliente;
            return pedido;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPedido
        {
            get
            {
                return _IdPedido;
            }
            set
            {
                if (_IdPedido != value)
                {
                    OnIdPedidoChanging(value);
                    ReportPropertyChanging("IdPedido");
                    _IdPedido = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdPedido");
                    OnIdPedidoChanged();
                }
            }
        }
        private global::System.Int32 _IdPedido;
        partial void OnIdPedidoChanging(global::System.Int32 value);
        partial void OnIdPedidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaPedido
        {
            get
            {
                return _FechaPedido;
            }
            set
            {
                OnFechaPedidoChanging(value);
                ReportPropertyChanging("FechaPedido");
                _FechaPedido = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaPedido");
                OnFechaPedidoChanged();
            }
        }
        private global::System.DateTime _FechaPedido;
        partial void OnFechaPedidoChanging(global::System.DateTime value);
        partial void OnFechaPedidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Importe
        {
            get
            {
                return _Importe;
            }
            set
            {
                OnImporteChanging(value);
                ReportPropertyChanging("Importe");
                _Importe = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Importe");
                OnImporteChanged();
            }
        }
        private global::System.Decimal _Importe;
        partial void OnImporteChanging(global::System.Decimal value);
        partial void OnImporteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientesIdCliente
        {
            get
            {
                return _ClientesIdCliente;
            }
            set
            {
                OnClientesIdClienteChanging(value);
                ReportPropertyChanging("ClientesIdCliente");
                _ClientesIdCliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientesIdCliente");
                OnClientesIdClienteChanged();
            }
        }
        private global::System.Int32 _ClientesIdCliente;
        partial void OnClientesIdClienteChanging(global::System.Int32 value);
        partial void OnClientesIdClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaEnvio
        {
            get
            {
                return _FechaEnvio;
            }
            set
            {
                OnFechaEnvioChanging(value);
                ReportPropertyChanging("FechaEnvio");
                _FechaEnvio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaEnvio");
                OnFechaEnvioChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaEnvio;
        partial void OnFechaEnvioChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaEnvioChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TiendaRegalosModel", "FK_Pedidos_Clientes", "Clientes")]
        public Cliente Clientes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("TiendaRegalosModel.FK_Pedidos_Clientes", "Clientes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("TiendaRegalosModel.FK_Pedidos_Clientes", "Clientes").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cliente> ClientesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("TiendaRegalosModel.FK_Pedidos_Clientes", "Clientes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cliente>("TiendaRegalosModel.FK_Pedidos_Clientes", "Clientes", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TiendaRegalosModel", "FK_RegalosPedido_Pedidos", "RegalosPedido")]
        public EntityCollection<RegaloPedido> RegalosPedido
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RegaloPedido>("TiendaRegalosModel.FK_RegalosPedido_Pedidos", "RegalosPedido");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RegaloPedido>("TiendaRegalosModel.FK_RegalosPedido_Pedidos", "RegalosPedido", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TiendaRegalosModel", Name="Regalo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Regalo : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Regalo.
        /// </summary>
        /// <param name="idRegalo">Valor inicial de la propiedad IdRegalo.</param>
        /// <param name="nombreRegalo">Valor inicial de la propiedad NombreRegalo.</param>
        /// <param name="precio">Valor inicial de la propiedad Precio.</param>
        /// <param name="categoriasIdCategoria">Valor inicial de la propiedad CategoriasIdCategoria.</param>
        public static Regalo CreateRegalo(global::System.Int32 idRegalo, global::System.String nombreRegalo, global::System.Decimal precio, global::System.Int32 categoriasIdCategoria)
        {
            Regalo regalo = new Regalo();
            regalo.IdRegalo = idRegalo;
            regalo.NombreRegalo = nombreRegalo;
            regalo.Precio = precio;
            regalo.CategoriasIdCategoria = categoriasIdCategoria;
            return regalo;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdRegalo
        {
            get
            {
                return _IdRegalo;
            }
            set
            {
                if (_IdRegalo != value)
                {
                    OnIdRegaloChanging(value);
                    ReportPropertyChanging("IdRegalo");
                    _IdRegalo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdRegalo");
                    OnIdRegaloChanged();
                }
            }
        }
        private global::System.Int32 _IdRegalo;
        partial void OnIdRegaloChanging(global::System.Int32 value);
        partial void OnIdRegaloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreRegalo
        {
            get
            {
                return _NombreRegalo;
            }
            set
            {
                OnNombreRegaloChanging(value);
                ReportPropertyChanging("NombreRegalo");
                _NombreRegalo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreRegalo");
                OnNombreRegaloChanged();
            }
        }
        private global::System.String _NombreRegalo;
        partial void OnNombreRegaloChanging(global::System.String value);
        partial void OnNombreRegaloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Precio
        {
            get
            {
                return _Precio;
            }
            set
            {
                OnPrecioChanging(value);
                ReportPropertyChanging("Precio");
                _Precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Precio");
                OnPrecioChanged();
            }
        }
        private global::System.Decimal _Precio;
        partial void OnPrecioChanging(global::System.Decimal value);
        partial void OnPrecioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Imagen
        {
            get
            {
                return _Imagen;
            }
            set
            {
                OnImagenChanging(value);
                ReportPropertyChanging("Imagen");
                _Imagen = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Imagen");
                OnImagenChanged();
            }
        }
        private global::System.String _Imagen;
        partial void OnImagenChanging(global::System.String value);
        partial void OnImagenChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoriasIdCategoria
        {
            get
            {
                return _CategoriasIdCategoria;
            }
            set
            {
                OnCategoriasIdCategoriaChanging(value);
                ReportPropertyChanging("CategoriasIdCategoria");
                _CategoriasIdCategoria = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoriasIdCategoria");
                OnCategoriasIdCategoriaChanged();
            }
        }
        private global::System.Int32 _CategoriasIdCategoria;
        partial void OnCategoriasIdCategoriaChanging(global::System.Int32 value);
        partial void OnCategoriasIdCategoriaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TiendaRegalosModel", "FK_Regalos_Categorias", "Categorias")]
        public Categoria Categorias
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("TiendaRegalosModel.FK_Regalos_Categorias", "Categorias").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("TiendaRegalosModel.FK_Regalos_Categorias", "Categorias").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Categoria> CategoriasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("TiendaRegalosModel.FK_Regalos_Categorias", "Categorias");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Categoria>("TiendaRegalosModel.FK_Regalos_Categorias", "Categorias", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TiendaRegalosModel", "FK_RegalosPedido_Regalos", "RegalosPedido")]
        public EntityCollection<RegaloPedido> RegalosPedido
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RegaloPedido>("TiendaRegalosModel.FK_RegalosPedido_Regalos", "RegalosPedido");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RegaloPedido>("TiendaRegalosModel.FK_RegalosPedido_Regalos", "RegalosPedido", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TiendaRegalosModel", Name="RegaloPedido")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RegaloPedido : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto RegaloPedido.
        /// </summary>
        /// <param name="pedidosIdPedido">Valor inicial de la propiedad PedidosIdPedido.</param>
        /// <param name="regalosIdRegalo">Valor inicial de la propiedad RegalosIdRegalo.</param>
        /// <param name="cantidad">Valor inicial de la propiedad Cantidad.</param>
        public static RegaloPedido CreateRegaloPedido(global::System.Int32 pedidosIdPedido, global::System.Int32 regalosIdRegalo, global::System.Int32 cantidad)
        {
            RegaloPedido regaloPedido = new RegaloPedido();
            regaloPedido.PedidosIdPedido = pedidosIdPedido;
            regaloPedido.RegalosIdRegalo = regalosIdRegalo;
            regaloPedido.Cantidad = cantidad;
            return regaloPedido;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PedidosIdPedido
        {
            get
            {
                return _PedidosIdPedido;
            }
            set
            {
                if (_PedidosIdPedido != value)
                {
                    OnPedidosIdPedidoChanging(value);
                    ReportPropertyChanging("PedidosIdPedido");
                    _PedidosIdPedido = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PedidosIdPedido");
                    OnPedidosIdPedidoChanged();
                }
            }
        }
        private global::System.Int32 _PedidosIdPedido;
        partial void OnPedidosIdPedidoChanging(global::System.Int32 value);
        partial void OnPedidosIdPedidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RegalosIdRegalo
        {
            get
            {
                return _RegalosIdRegalo;
            }
            set
            {
                if (_RegalosIdRegalo != value)
                {
                    OnRegalosIdRegaloChanging(value);
                    ReportPropertyChanging("RegalosIdRegalo");
                    _RegalosIdRegalo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RegalosIdRegalo");
                    OnRegalosIdRegaloChanged();
                }
            }
        }
        private global::System.Int32 _RegalosIdRegalo;
        partial void OnRegalosIdRegaloChanging(global::System.Int32 value);
        partial void OnRegalosIdRegaloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cantidad
        {
            get
            {
                return _Cantidad;
            }
            set
            {
                OnCantidadChanging(value);
                ReportPropertyChanging("Cantidad");
                _Cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cantidad");
                OnCantidadChanged();
            }
        }
        private global::System.Int32 _Cantidad;
        partial void OnCantidadChanging(global::System.Int32 value);
        partial void OnCantidadChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TiendaRegalosModel", "FK_RegalosPedido_Pedidos", "Pedidos")]
        public Pedido Pedidos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pedido>("TiendaRegalosModel.FK_RegalosPedido_Pedidos", "Pedidos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pedido>("TiendaRegalosModel.FK_RegalosPedido_Pedidos", "Pedidos").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pedido> PedidosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pedido>("TiendaRegalosModel.FK_RegalosPedido_Pedidos", "Pedidos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pedido>("TiendaRegalosModel.FK_RegalosPedido_Pedidos", "Pedidos", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TiendaRegalosModel", "FK_RegalosPedido_Regalos", "Regalos")]
        public Regalo Regalos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Regalo>("TiendaRegalosModel.FK_RegalosPedido_Regalos", "Regalos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Regalo>("TiendaRegalosModel.FK_RegalosPedido_Regalos", "Regalos").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Regalo> RegalosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Regalo>("TiendaRegalosModel.FK_RegalosPedido_Regalos", "Regalos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Regalo>("TiendaRegalosModel.FK_RegalosPedido_Regalos", "Regalos", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
